add check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -41,6 +41,16 @@ jobs:
     - name: Install built package
       run: |
         pip install dist/*.whl
+    - name: Run
+      run: |
+        set +e
+        output=$(carconnectivity test/integration_test/carConnectivity.json 2>&1)
+        echo "$output" | grep -q 'There was a problem with the configuration: No MQTT broker specified in config ("broker" missing)'
+        if [ $? -ne 0 ]; then
+          echo "$output"
+          exit 1
+        fi
+        set -e
     - name: Lint
       run: |
         make lint
